---
title: "ProblemSet3_3"
author: 'Name: Zhen Qin, Uniqname: qinzhen, UMID: 48800866, Dept: Statistics'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The data is from https://github.com/jensqin/Stat506.

####a.

```{r, eval=FALSE, message=FALSE, warning=FALSE, include=TRUE}
# Execute AirportCodesWebScrape.R from my github
# source("AirportCodesWebScrape.R")

.libPaths('~/Rlib')
#install.packages('rvest')
library(rvest)
library(data.table)
library(tidyverse)
library(stringr)
library(parallel)


# Extract the information we want from the resulting string
get_miles = function(txt){
  y = str_split(txt,'\\(')[[1]]
  z = str_split(y[2],' ')[[1]][1]
  as.numeric(z)
}


## Encapsulate the above in a function to find the distance 
## between two valid airport codes.
scrape_dist = function(a1, a2){
  
  url = sprintf('https://www.world-airport-codes.com/distance/?a1=%s&a2=%s',
                a1, a2)
  
  srch = read_html(url)
  txt =
    srch %>%
    html_node("strong") %>% # identified by viewing the source in a browser
    html_text() 
  get_miles(txt)
}


## Now we can loop over all airports in the NYCflights14 data.
nyc14 = fread('https://github.com/arunsrinivasan/flights/wiki/NYCflights14/flights14.csv')

# unique codes
origin_codes = unique(nyc14$origin)
dest_codes = unique(nyc14$dest)

# call scrape_dist for a single fixed code vs a set of targets
get_dists = function(fixed, targets){
  dists = sapply(targets, function(target) scrape_dist(fixed, target))
  tibble(from=fixed, to=targets, dist=dists)
}


# Exexute outer loop in parallel.
inner_loop =  function(i){
  get_dists(origin_codes[i], origin_codes[{i+1}:length(origin_codes)])
}

## May not work on servers with limited ports.
#df_dist = mclapply(107:{length(dest_codes)-1}, inner_loop) 

origin_dist = list()
for(i in 1:{length(origin_codes)-1}){
  origin_dist[[i]] = inner_loop(i)
}

# bind results of inner loop into a single data frame
origin_dist = do.call(bind_rows, origin_dist)

outer_loop = function(i){
  get_dists(origin_codes[i], dest_codes)
}

dest_dist = list()
for(i in 1:length(origin_codes)){
  dest_dist[[i]] = outer_loop(i)
}

dest_dist = do.call(bind_rows, dest_dist)

fromo_dist = rbind(origin_dist, dest_dist)

save(fromo_dist, file='./AirportCodeDistsFromOrigin.RData')
```

####b.

```{r, message=FALSE, warning=FALSE}
# Get prepared
setwd("E:/UM academy/stat 506/ProblemSet3")
library(rvest)
library(data.table)
library(tidyverse)
library(stringr)
library(ggplot2)

# load data and combine the distances from part a
load("AirportCodeDists.RData")
load("AirportCodeDistsFromOrigin.RData")
df = rbind(df_dist, fromo_dist)
tmpdf=data.table(from=df$to,to=df$from,dist=df$dist)
df = rbind(df,tmpdf)
df_cast = dcast(df, from~to, value.var="dist",fill=0)
rownames(df_cast)<-df_cast$from
knitr::kable(df_cast[1:5,1:6])

# get 112 by 112 dataset
df_cast = df_cast[,-1]
```

####c.

```{r}
# Use multidimensional scaling to produce a two-dimensional map
mds=cmdscale(df_cast)
rownames(mds)=colnames(df_cast)
colnames(mds)=c("V1","V2")
ggplot(data = as.tibble(mds), aes(x=V1, y=V2)) +geom_point()+ 
  geom_text(aes(label=rownames(mds)),hjust=0,vjust=0)+ggtitle("two-dimensional map")
save(df_cast,mds,file="./ProblemSet3_3.RData")
```